/*
 * Copyright © 2002-2017 Bluebeam Software, Inc. All Rights Reserved.
 * Creator: Jonathan Rothberg
 */

use std::sync::Arc;
use std::io::{Write};
use std::fs::File;
use generator::typer::Typer;
use generator::ident_style::{IdentStyleDefault, IdentConverter};

pub struct Spec<'a> {
    // pub root: String,
    // pub cpp_root: String,
    pub typer: Typer,
    pub java_out_folder: Option<&'a str>,
    pub java_package: Option<&'a str>,
    pub java_class_access_modifier: &'a str,
    pub java_ident_style: IdentStyleDefault,
    pub java_cpp_exception: Option<&'a str>,
    pub java_annotation: Option<&'a str>,
    pub java_nullable_annotation: Option<&'a str>,
    pub java_nonnullable_annotation: Option<&'a str>,
    pub java_use_final_for_record: bool,
    pub cpp_out_folder: Option<&'a str>,
    pub cpp_header_out_folder: Option<&'a str>,
    pub cpp_include_prefix: &'a str,
    pub cpp_extended_record_include_prefix: &'a str,
    pub cpp_namespace: &'a str,
    pub cpp_ident_style: IdentStyleDefault,
    pub cpp_file_ident_style: Arc<IdentConverter>,
    pub cpp_optional_template: &'a str,
    pub cpp_optional_header: &'a str,
    pub cpp_enum_has_workaround: bool,
    pub cpp_nn_header: Option<&'a str>,
    pub cpp_nn_type: Option<&'a str>,
    pub cpp_nn_check_expression: Option<&'a str>,
    pub cpp_use_wide_strings: bool,
    pub jni_out_folder: Option<&'a str>,
    pub jni_header_out_folder: Option<&'a str>,
    pub jni_include_prefix: &'a str,
    pub jni_include_cpp_prefix: &'a str,
    pub jni_namespace: &'a str,
    pub jni_class_ident_style: Arc<IdentConverter>,
    pub jni_file_ident_style: Arc<IdentConverter>,
    pub jni_base_lib_include_prefix: &'a str,
    pub cpp_ext: &'a str,
    pub cpp_header_ext: &'a str,
    pub objc_out_folder: Option<&'a str>,
    pub objc_cpp_out_folder: Option<&'a str>,
    pub objc_ident_style: IdentStyleDefault,
    pub objc_file_ident_style: Arc<IdentConverter>,
    pub objc_cpp_ext: &'a str,
    pub objc_header_ext: &'a str,
    pub objc_include_prefix: &'a str,
    pub objc_extended_record_include_prefix: &'a str,
    pub objc_cpp_include_prefix: &'a str,
    pub objc_cpp_include_cpp_prefix: &'a str,
    pub objc_cpp_include_objc_prefix: &'a str,
    pub objc_cpp_namespace: &'a str,
    pub objc_base_lib_include_prefix: &'a str,
    pub out_file_list_writer: Option<Arc<File>>,
    pub skip_generation: bool,
    pub yaml_out_folder: Option<&'a str>,
    pub yaml_out_file: Option<&'a str>,
    pub yaml_prefix: &'a str
}

impl<'a> Spec<'a> {
    pub fn new(
        // root: String,
        //        cpp_root: String,
               typer: Typer,
               java_out_folder: Option<&'a str>,
               java_package: Option<&'a str>,
               java_class_access_modifier: &'a str,
               java_ident_style: IdentStyleDefault,
               java_cpp_exception: Option<&'a str>,
               java_annotation: Option<&'a str>,
               java_nullable_annotation: Option<&'a str>,
               java_nonnullable_annotation: Option<&'a str>,
               java_use_final_for_record: bool,
               cpp_out_folder: Option<&'a str>,
               cpp_header_out_folder: Option<&'a str>,
               cpp_include_prefix: &'a str,
               cpp_extended_record_include_prefix: &'a str,
               cpp_namespace: &'a str,
               cpp_ident_style: IdentStyleDefault,
               cpp_file_ident_style: Arc<IdentConverter>,
               cpp_optional_template: &'a str,
               cpp_optional_header: &'a str,
               cpp_enum_has_workaround: bool,
               cpp_nn_header: Option<&'a str>,
               cpp_nn_type: Option<&'a str>,
               cpp_nn_check_expression: Option<&'a str>,
               cpp_use_wide_strings: bool,
               jni_out_folder: Option<&'a str>,
               jni_header_out_folder: Option<&'a str>,
               jni_include_prefix: &'a str,
               jni_include_cpp_prefix: &'a str,
               jni_namespace: &'a str,
               jni_class_ident_style: Arc<IdentConverter>,
               jni_file_ident_style: Arc<IdentConverter>,
               jni_base_lib_include_prefix: &'a str,
               cpp_ext: &'a str,
               cpp_header_ext: &'a str,
               objc_out_folder: Option<&'a str>,
               objc_cpp_out_folder: Option<&'a str>,
               objc_ident_style: IdentStyleDefault,
               objc_file_ident_style: Arc<IdentConverter>,
               objc_cpp_ext: &'a str,
               objc_header_ext: &'a str,
               objc_include_prefix: &'a str,
               objc_extended_record_include_prefix: &'a str,
               objc_cpp_include_prefix: &'a str,
               objc_cpp_include_cpp_prefix: &'a str,
               objc_cpp_include_objc_prefix: &'a str,
               objc_cpp_namespace: &'a str,
               objc_base_lib_include_prefix: &'a str,
               out_file_list_writer: Option<Arc<File>>,
               skip_generation: bool,
               yaml_out_folder: Option<&'a str>,
               yaml_out_file: Option<&'a str>,
               yaml_prefix: &'a str
            ) -> Spec<'a> {
        Spec{
            // root: root,
            // cpp_root: cpp_root,
            typer: typer,
            java_out_folder: java_out_folder,
            java_package: java_package,
            java_class_access_modifier: java_class_access_modifier,
            java_ident_style: java_ident_style,
            java_cpp_exception: java_cpp_exception,
            java_annotation: java_annotation,
            java_nullable_annotation: java_nullable_annotation,
            java_nonnullable_annotation: java_nonnullable_annotation,
            java_use_final_for_record: java_use_final_for_record,
            cpp_out_folder: cpp_out_folder,
            cpp_header_out_folder: cpp_header_out_folder,
            cpp_include_prefix: cpp_include_prefix,
            cpp_extended_record_include_prefix: cpp_extended_record_include_prefix,
            cpp_namespace: cpp_namespace,
            cpp_ident_style: cpp_ident_style,
            cpp_file_ident_style: cpp_file_ident_style,
            cpp_optional_template: cpp_optional_template,
            cpp_optional_header: cpp_optional_header,
            cpp_enum_has_workaround: cpp_enum_has_workaround,
            cpp_nn_header: cpp_nn_header,
            cpp_nn_type: cpp_nn_type,
            cpp_nn_check_expression: cpp_nn_check_expression,
            cpp_use_wide_strings: cpp_use_wide_strings,
            jni_out_folder: jni_out_folder,
            jni_header_out_folder: jni_header_out_folder,
            jni_include_prefix: jni_include_prefix,
            jni_include_cpp_prefix: jni_include_cpp_prefix,
            jni_namespace: jni_namespace,
            jni_class_ident_style: jni_class_ident_style,
            jni_file_ident_style: jni_file_ident_style,
            jni_base_lib_include_prefix: jni_base_lib_include_prefix,
            cpp_ext: cpp_ext,
            cpp_header_ext: cpp_header_ext,
            objc_out_folder: objc_out_folder,
            objc_cpp_out_folder: objc_cpp_out_folder,
            objc_ident_style: objc_ident_style,
            objc_file_ident_style: objc_file_ident_style,
            objc_cpp_ext: objc_cpp_ext,
            objc_header_ext: objc_header_ext,
            objc_include_prefix: objc_include_prefix,
            objc_extended_record_include_prefix: objc_extended_record_include_prefix,
            objc_cpp_include_prefix: objc_cpp_include_prefix,
            objc_cpp_include_cpp_prefix: objc_cpp_include_cpp_prefix,
            objc_cpp_include_objc_prefix: objc_cpp_include_objc_prefix,
            objc_cpp_namespace: objc_cpp_namespace,
            objc_base_lib_include_prefix: objc_base_lib_include_prefix,
            out_file_list_writer: out_file_list_writer,
            skip_generation: skip_generation,
            yaml_out_folder: yaml_out_folder,
            yaml_out_file: yaml_out_file,
            yaml_prefix: yaml_prefix
        }
    }

    // fn pass_through(input: String) -> String {
    //     input
    // }
}
