// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by rusty_lamp
#pragma once
#include <unordered_set>
#include <vector>

namespace namespace_gen {
struct record_dup {
std::vector one;
std::unordered_set two;
double three;
};
}
