// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by rusty_lamp
#pragma once
#include <string>

namespace namespace_gen {
struct record_test {
int32_t one;
float two;
std::string three;
};
}
